instanceId:
  configValueCount: "LIST"
  configValueType: "BOOLEAN"
  displayName: "dd"
  description: "The name of tdddddhe instance. Should be unique per installation"
  sectionName: "General"
  encrypted: false
  rule: "${instanceId} != null"
  restartRequired: null
  defaultValue: null
spring:
  configValueCount: "LIST"
  configValueType: "CUSTOM"
  displayName: "Call Listen Port"
  description: "callListeningGatewayList skip CTI Lookup and Extension Lookup for\
    \ IP List"
  sectionName: "CallListenind"
  encrypted: false
  rule: "${spring}.?[#this.get('devtools').get('restart').get('enabled') eq false].size()\
    \ == 1 and ${spring}.?[['datasource'][0]['password'] eq 'sa'].size() == 1"
  restartRequired: null
  defaultValue: null
